// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN232.Lab1.CoffeeStore.Repository.Models;

public partial class ProductInMenu
{
    public int ProductInMenuId { get; set; }

    public int ProductId { get; set; }

    public int MenuId { get; set; }

    public int Quantity { get; set; }

    public virtual Menu Menu { get; set; }

    public virtual Product Product { get; set; }
}